name: draughts
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - anyio=4.12.1
  - aom=3.9.1
  - appnope=0.1.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.1.0
  - attrs=25.4.0
  - babel=2.17.0
  - backports.zstd=1.3.0
  - beautifulsoup4=4.14.3
  - blas=1.0
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.11.14
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.19
  - decorator=5.2.1
  - defusedxml=0.7.1
  - double-conversion=3.4.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - farama-notifications=0.0.4
  - ffmpeg=8.0.1
  - filelock=3.20.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.44.4
  - glslang=16.1.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - gymnasium=1.2.2
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.3.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - imath=3.2.2
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=7.1.0
  - ipython=9.9.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jasper=4.2.8
  - jax-jumpy=1.0.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - json5=0.13.0
  - jsonpointer=3.0.0
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.26.0
  - jupyter-lsp=2.3.0
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.4
  - jupyterlab=4.5.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lark=1.3.1
  - lcms2=2.18
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libass=0.17.4
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=20.1.8
  - libcurl=8.18.0
  - libcxx=20.1.8
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.3
  - libhwloc=2.12.2
  - libhwy=1.3.0
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm19=19.1.7
  - libllvm20=20.1.8
  - liblzma=5.8.2
  - liblzma-devel=5.8.2
  - libnghttp2=1.67.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopencv=4.12.0
  - libopenvino=2025.4.1
  - libopenvino-arm-cpu-plugin=2025.4.1
  - libopenvino-auto-batch-plugin=2025.4.1
  - libopenvino-auto-plugin=2025.4.1
  - libopenvino-hetero-plugin=2025.4.1
  - libopenvino-ir-frontend=2025.4.1
  - libopenvino-onnx-frontend=2025.4.1
  - libopenvino-paddle-frontend=2025.4.1
  - libopenvino-pytorch-frontend=2025.4.1
  - libopenvino-tensorflow-frontend=2025.4.1
  - libopenvino-tensorflow-lite-frontend=2025.4.1
  - libopus=1.6.1
  - libpng=1.6.54
  - libpq=18.1
  - libprotobuf=6.31.1
  - librsvg=2.60.0
  - libsodium=1.0.20
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libusb=1.0.29
  - libvorbis=1.3.7
  - libvpx=1.15.2
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mistune=3.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - narwhals=2.15.0
  - nbclient=0.10.4
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6.1
  - notebook=7.5.2
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - opencv=4.12.0
  - openexr=3.4.4
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openjph=0.26.0
  - openldap=2.6.10
  - openssl=3.6.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - pango=1.56.4
  - parso=0.8.5
  - patsy=1.0.2
  - pcre2=10.47
  - pexpect=4.9.0
  - pillow=12.1.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - plotly=6.5.2
  - prometheus_client=0.24.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pure_eval=0.2.3
  - py-opencv=4.12.0
  - pycparser=2.22
  - pygments=2.19.2
  - pyobjc-core=12.1
  - pyobjc-framework-cocoa=12.1
  - pyparsing=3.3.1
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytorch=2.5.1
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.10.1
  - rav1e=0.7.1
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.30.0
  - scikit-learn=1.3.1
  - scipy=1.17.0
  - sdl2=2.32.56
  - sdl3=3.2.30
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=2.1.0
  - setuptools=80.10.1
  - shaderc=2025.5
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8.2
  - spirv-tools=2025.4
  - sqlite=3.51.1
  - stack_data=0.6.3
  - statsmodels=0.14.6
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2022.3.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.5.1
  - tk=8.6.15
  - tomli=2.4.0
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - urllib3=2.6.3
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.2
  - xz-gpl-tools=5.8.2
  - xz-tools=5.8.2
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - alembic==1.18.1
      - colorlog==6.10.1
      - dotenv==0.9.9
      - mako==1.3.10
      - optuna==4.7.0
      - python-dotenv==1.2.1
      - sqlalchemy==2.0.45
prefix: /opt/anaconda3/envs/draughts
