name: draughts
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - anyio=4.12.1=pyhcf101f3_0
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h9408147_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.1.0=pyhcf101f3_0
  - attrs=25.4.0=pyhcf101f3_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.3.0=py311hee243d0_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - blas=1.0=openblas
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - brotli-python=1.2.0=py311hdc60ec4_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=he0f2337_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py311hd10dc20_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h7d85929_4
  - cpython=3.11.14=py311hd8ed1ab_2
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=h3ff7a7c_1
  - debugpy=1.8.19=py311hc58e375_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - double-conversion=3.4.0=haf25636_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - farama-notifications=0.0.4=pyhd8ed1ab_0
  - ffmpeg=8.0.1=gpl_h1511fcb_109
  - filelock=3.20.3=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py311ha9b3269_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - gdk-pixbuf=2.44.4=h7542897_0
  - glslang=16.1.0=h60b4770_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py311hd340a2e_2
  - graphite2=1.3.14=hec049ff_2
  - gymnasium=1.2.2=np2py311he8d3834_0
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.0=h3103d1b_0
  - hdf5=1.14.6=nompi_h51e7c0a_105
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h38cb7af_0
  - idna=3.11=pyhd8ed1ab_0
  - imath=3.2.2=h3470cca_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.9.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jasper=4.2.8=hc0e5025_0
  - jax-jumpy=1.0.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json5=0.13.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.26.0=hcf101f3_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.4=pyhcf101f3_0
  - jupyterlab=4.5.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - kiwisolver=1.4.9=py311h26d6576_2
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.18=hdfa7624_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.4=h51d1e36_0
  - libass=0.17.4=hcbd7ca7_0
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.9.0=1_h2ec9a88_netlib
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.9.0=13_hd5b1ab5_netlib
  - libclang-cpp19.1=19.1.7=default_hf3020a7_7
  - libclang13=20.1.8=default_h13b06bd_8
  - libcurl=8.18.0=he38603e_0
  - libcxx=20.1.8=hf598326_3
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libglib=2.86.3=hfe11c1f_0
  - libhwloc=2.12.2=default_ha3cc4f2_1000
  - libhwy=1.3.0=h48b13b8_1
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - libjxl=0.11.1=h913acd8_8
  - liblapack=3.9.0=13_ha522803_netlib
  - liblapacke=3.9.0=13_he191fbd_netlib
  - libllvm19=19.1.7=h8e0c9ce_2
  - libllvm20=20.1.8=h8e0c9ce_1
  - liblzma=5.8.2=h8088a28_0
  - liblzma-devel=5.8.2=h8088a28_0
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=hf2bb037_2
  - libopencv=4.12.0=qt6_py311h1578702_612
  - libopenvino=2025.4.1=he5d468a_0
  - libopenvino-arm-cpu-plugin=2025.4.1=he5d468a_0
  - libopenvino-auto-batch-plugin=2025.4.1=h0b5e12f_0
  - libopenvino-auto-plugin=2025.4.1=h0b5e12f_0
  - libopenvino-hetero-plugin=2025.4.1=hf51539c_0
  - libopenvino-ir-frontend=2025.4.1=hf51539c_0
  - libopenvino-onnx-frontend=2025.4.1=h9101cd2_0
  - libopenvino-paddle-frontend=2025.4.1=h9101cd2_0
  - libopenvino-pytorch-frontend=2025.4.1=haf25636_0
  - libopenvino-tensorflow-frontend=2025.4.1=h6089731_0
  - libopenvino-tensorflow-lite-frontend=2025.4.1=haf25636_0
  - libopus=1.6.1=h1a92334_0
  - libpng=1.6.54=h132b30e_0
  - libpq=18.1=h6caddbb_3
  - libprotobuf=6.31.1=h98f38fd_4
  - librsvg=2.60.0=h5c55ec3_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.2=h1ae2325_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h4030677_1
  - libusb=1.0.29=hbc156a2_0
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.15.2=ha759d40_0
  - libvulkan-loader=1.4.328.1=h49c215f_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h8d039ee_1
  - libxml2-16=2.15.1=h5ef1a60_1
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=15.0.7=h7cfbb63_0
  - markupsafe=3.0.3=py311ha9b3269_0
  - matplotlib=3.10.8=py311ha1ab1f8_0
  - matplotlib-base=3.10.8=py311h29553df_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.2.0=pyhcf101f3_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.15.0=pyhcf101f3_0
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6.1=pyhcf101f3_0
  - notebook=7.5.2=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=1.26.4=py311h7125741_0
  - opencv=4.12.0=qt6_py311hdb2d507_612
  - openexr=3.4.4=he0ec429_1
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openjph=0.26.0=h2a4d681_0
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.6.0=h5503f6c_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hdb8e4fa_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.4=h875632e_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.47=h30297fc_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.1.0=py311hd37aea2_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - plotly=6.5.2=pyhd8ed1ab_0
  - prometheus_client=0.24.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.1=py311he363849_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=hd3d436d_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.12.0=qt6_py311he96805e_612
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyobjc-core=12.1=py311hce6e4fa_0
  - pyobjc-framework-cocoa=12.1=py311h9049b8e_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=h18782d2_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytorch=2.5.1=py3.11_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311ha9b3269_0
  - pyzmq=27.1.0=py311h13abfa4_0
  - qhull=2020.2=h420ef59_5
  - qt6-main=6.10.1=h9aec236_4
  - rav1e=0.7.1=h0716509_3
  - readline=8.3=h0b18652_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.30.0=py311h71babbd_0
  - scikit-learn=1.3.1=py311hf0b18b8_0
  - scipy=1.17.0=py311he9931d0_1
  - sdl2=2.32.56=h248ca61_0
  - sdl3=3.2.30=h6fa9c73_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=2.1.0=pyh5552912_0
  - setuptools=80.10.1=pyh332efcf_0
  - shaderc=2025.5=h1a5098f_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.2=pyhd8ed1ab_0
  - spirv-tools=2025.4=ha7d2532_0
  - sqlite=3.51.1=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py311h09efe57_0
  - svt-av1=3.1.2=h12ba402_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=h4ddebb9_2
  - terminado=0.18.1=pyhc90fa1f_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.15=hcd8a7d5_0
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.5.4=py311h9408147_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h8577fbf_1
  - unicodedata2=17.0.0=py311h9408147_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xz=5.8.2=hd0f0c4f_0
  - xz-gpl-tools=5.8.2=hd0f0c4f_0
  - xz-tools=5.8.2=h8088a28_0
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.3.2=hed4e4f5_1
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - alembic==1.18.1
      - colorlog==6.10.1
      - dotenv==0.9.9
      - mako==1.3.10
      - optuna==4.7.0
      - pygame==2.6.1
      - python-dotenv==1.2.1
      - sqlalchemy==2.0.45
prefix: /opt/anaconda3/envs/draughts
